// Auto-generated combined data from Excel parts 1–4

const EVENT = {
  "title": "COLUMBINA",
  "subtitle": "Итоги ивента",
  "cover": "img/cover.png",
  "stats": "",
  "credits": [
    {
      "role": "Организатор",
      "name": "COLUMBINA",
      "note": "Автор идеи, ведущий и судья ивента."
    },
    {
      "role": "Судейство",
      "name": "Оценка /10",
      "note": "Работы оценивались по 10-балльной шкале без комментариев."
    },
    {
      "role": "Музыка",
      "name": "theme.mp3",
      "note": "Фоновая музыка сайта."
    },
    {
      "role": "Участники",
      "name": "Artists",
      "note": "Каждая работа стала частью архива."
    }
  ]
};

const WORKS = [
  {
    "id": 1,
    "username": "@ab_alyona",
    "title": "Работа #1",
    "image": "img/works/001_ab_alyona.webp",
    "postLink": "https://t.me/StableWaifuComments/17627396",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 2,
    "username": "@ab_alyona",
    "title": "Работа #2",
    "image": "img/works/002_ab_alyona.webp",
    "postLink": "https://t.me/StableWaifuComments/17663562",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 3,
    "username": "@ab_alyona",
    "title": "Работа #3",
    "image": "img/works/003_ab_alyona.webp",
    "postLink": "https://t.me/StableWaifuComments/17664427",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 4,
    "username": "@ab_alyona",
    "title": "Работа #4",
    "image": "img/works/004_ab_alyona.webp",
    "postLink": "https://t.me/StableWaifuComments/17663987",
    "score": 10,
    "reward": 2100,
    "isWinner": true,
    "place": 1,
    "awardTitle": "Grand Winner"
  },
  {
    "id": 5,
    "username": "@alenxxz",
    "title": "Работа #5",
    "image": "img/works/005_alenxxz.webp",
    "postLink": "https://t.me/StableWaifuComments/17629996",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 6,
    "username": "@alenxxz",
    "title": "Работа #6",
    "image": "img/works/006_alenxxz.webp",
    "postLink": "https://t.me/StableWaifuComments/17630348",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 7,
    "username": "@alenxxz",
    "title": "Работа #7",
    "image": "img/works/007_alenxxz.webp",
    "postLink": "https://t.me/StableWaifuComments/17630529",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 8,
    "username": "@alenxxz",
    "title": "Работа #8",
    "image": "img/works/008_alenxxz.webp",
    "postLink": "https://t.me/StableWaifuComments/17632640",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 9,
    "username": "@alenxxz",
    "title": "Работа #9",
    "image": "img/works/009_alenxxz.webp",
    "postLink": "https://t.me/StableWaifuComments/17636889",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 10,
    "username": "@alenxxz",
    "title": "Работа #10",
    "image": "img/works/010_alenxxz.webp",
    "postLink": "https://t.me/StableWaifuComments/17641524",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 11,
    "username": "@alenxxz",
    "title": "Работа #11",
    "image": "img/works/011_alenxxz.webp",
    "postLink": "https://t.me/StableWaifuComments/17631148",
    "score": 10,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 12,
    "username": "@amebaaaaaa",
    "title": "Работа #12",
    "image": "img/works/012_amebaaaaaa.webp",
    "postLink": "https://t.me/StableWaifuComments/17631863",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 13,
    "username": "@amebaaaaaa",
    "title": "Работа #13",
    "image": "img/works/013_amebaaaaaa.webp",
    "postLink": "https://t.me/StableWaifuComments/17631646",
    "score": 7,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 14,
    "username": "@AndrewTheApostol",
    "title": "Работа #14",
    "image": "img/works/014_AndrewTheApostol.webp",
    "postLink": "https://t.me/StableWaifuComments/17628835",
    "score": 4,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 15,
    "username": "@AndrewTheApostol",
    "title": "Работа #15",
    "image": "img/works/015_AndrewTheApostol.webp",
    "postLink": "https://t.me/StableWaifuComments/17628995",
    "score": 4,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 16,
    "username": "@AndrewTheApostol",
    "title": "Работа #16",
    "image": "img/works/016_AndrewTheApostol.webp",
    "postLink": "https://t.me/StableWaifuComments/17629014",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 17,
    "username": "@AndrewTheApostol",
    "title": "Работа #17",
    "image": "img/works/017_AndrewTheApostol.webp",
    "postLink": "https://t.me/StableWaifuComments/17629165",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 18,
    "username": "@AndrewTheApostol",
    "title": "Работа #18",
    "image": "img/works/018_AndrewTheApostol.webp",
    "postLink": "https://t.me/StableWaifuComments/17629093",
    "score": 6,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 19,
    "username": "@AngelinaKostritsa",
    "title": "Работа #19",
    "image": "img/works/019_AngelinaKostritsa.webp",
    "postLink": "https://t.me/StableWaifuComments/17624238",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 20,
    "username": "@AngelinaKostritsa",
    "title": "Работа #20",
    "image": "img/works/020_AngelinaKostritsa.webp",
    "postLink": "https://t.me/StableWaifuComments/17624320",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 21,
    "username": "@AngelinaKostritsa",
    "title": "Работа #21",
    "image": "img/works/021_AngelinaKostritsa.webp",
    "postLink": "https://t.me/StableWaifuComments/17624336",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 22,
    "username": "@AngelinaKostritsa",
    "title": "Работа #22",
    "image": "img/works/022_AngelinaKostritsa.webp",
    "postLink": "https://t.me/StableWaifuComments/17624512",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 23,
    "username": "@AngelinaKostritsa",
    "title": "Работа #23",
    "image": "img/works/023_AngelinaKostritsa.webp",
    "postLink": "https://t.me/StableWaifuComments/17624463",
    "score": 9,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 24,
    "username": "@angelus_solis545",
    "title": "Работа #24",
    "image": "img/works/024_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17631463",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 25,
    "username": "@angelus_solis545",
    "title": "Работа #25",
    "image": "img/works/025_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17631531",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 26,
    "username": "@angelus_solis545",
    "title": "Работа #26",
    "image": "img/works/026_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17631620",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 27,
    "username": "@angelus_solis545",
    "title": "Работа #27",
    "image": "img/works/027_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17632883",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 28,
    "username": "@angelus_solis545",
    "title": "Работа #28",
    "image": "img/works/028_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17634065",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 29,
    "username": "@angelus_solis545",
    "title": "Работа #29",
    "image": "img/works/029_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17636517",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 30,
    "username": "@angelus_solis545",
    "title": "Работа #30",
    "image": "img/works/030_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17642356",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 31,
    "username": "@angelus_solis545",
    "title": "Работа #31",
    "image": "img/works/031_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17642469",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 32,
    "username": "@angelus_solis545",
    "title": "Работа #32",
    "image": "img/works/032_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17642563",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 33,
    "username": "@angelus_solis545",
    "title": "Работа #33",
    "image": "img/works/033_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17649170",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 34,
    "username": "@angelus_solis545",
    "title": "Работа #34",
    "image": "img/works/034_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17649939",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 35,
    "username": "@angelus_solis545",
    "title": "Работа #35",
    "image": "img/works/035_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17652766",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 36,
    "username": "@angelus_solis545",
    "title": "Работа #36",
    "image": "img/works/036_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17655781",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 37,
    "username": "@angelus_solis545",
    "title": "Работа #37",
    "image": "img/works/037_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17658011",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 38,
    "username": "@angelus_solis545",
    "title": "Работа #38",
    "image": "img/works/038_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17663023",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 39,
    "username": "@angelus_solis545",
    "title": "Работа #39",
    "image": "img/works/039_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17663033",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 40,
    "username": "@angelus_solis545",
    "title": "Работа #40",
    "image": "img/works/040_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17663916",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 41,
    "username": "@angelus_solis545",
    "title": "Работа #41",
    "image": "img/works/041_angelus_solis545.webp",
    "postLink": "https://t.me/StableWaifuComments/17642183",
    "score": 9,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 42,
    "username": "@annakonigin",
    "title": "Работа #42",
    "image": "img/works/042_annakonigin.webp",
    "postLink": "https://t.me/StableWaifuComments/17631583",
    "score": 6,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 43,
    "username": "@astoryhetoldtwice",
    "title": "Работа #43",
    "image": "img/works/043_astoryhetoldtwice.webp",
    "postLink": "https://t.me/StableWaifuComments/17628566",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 44,
    "username": "@astoryhetoldtwice",
    "title": "Работа #44",
    "image": "img/works/044_astoryhetoldtwice.webp",
    "postLink": "https://t.me/StableWaifuComments/17630354",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 45,
    "username": "@astoryhetoldtwice",
    "title": "Работа #45",
    "image": "img/works/045_astoryhetoldtwice.webp",
    "postLink": "https://t.me/StableWaifuComments/17630021",
    "score": 10,
    "reward": 1300,
    "isWinner": true,
    "place": 2,
    "awardTitle": "Silver Moon"
  },
  {
    "id": 46,
    "username": "@avrilvb",
    "title": "Работа #46",
    "image": "img/works/046_avrilvb.webp",
    "postLink": "https://t.me/StableWaifuComments/17629378",
    "score": 7,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 47,
    "username": "@Benny_Shmidt",
    "title": "Работа #47",
    "image": "img/works/047_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17632820",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 48,
    "username": "@Benny_Shmidt",
    "title": "Работа #48",
    "image": "img/works/048_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17643119",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 49,
    "username": "@Benny_Shmidt",
    "title": "Работа #49",
    "image": "img/works/049_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17643333",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 50,
    "username": "@Benny_Shmidt",
    "title": "Работа #50",
    "image": "img/works/050_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17653412",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 51,
    "username": "@Benny_Shmidt",
    "title": "Работа #51",
    "image": "img/works/051_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17653772",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 52,
    "username": "@Benny_Shmidt",
    "title": "Работа #52",
    "image": "img/works/052_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17654004",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 53,
    "username": "@Benny_Shmidt",
    "title": "Работа #53",
    "image": "img/works/053_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17654192",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 54,
    "username": "@Benny_Shmidt",
    "title": "Работа #54",
    "image": "img/works/054_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17663971",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 55,
    "username": "@Benny_Shmidt",
    "title": "Работа #55",
    "image": "img/works/055_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17664049",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 56,
    "username": "@Benny_Shmidt",
    "title": "Работа #56",
    "image": "img/works/056_Benny_Shmidt.webp",
    "postLink": "https://t.me/StableWaifuComments/17664244",
    "score": 9,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 57,
    "username": "@Chtozapizdetz",
    "title": "Работа #57",
    "image": "img/works/057_Chtozapizdetz.webp",
    "postLink": "https://t.me/StableWaifuComments/17624394",
    "score": 7,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 58,
    "username": "@DBcrimson",
    "title": "Работа #58",
    "image": "img/works/058_DBcrimson.webp",
    "postLink": "https://t.me/StableWaifuComments/17641124?single",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 59,
    "username": "@DBcrimson",
    "title": "Работа #59",
    "image": "img/works/059_DBcrimson.webp",
    "postLink": "https://t.me/StableWaifuComments/17641207",
    "score": 3,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 60,
    "username": "@DBcrimson",
    "title": "Работа #60",
    "image": "img/works/060_DBcrimson.webp",
    "postLink": "https://t.me/StableWaifuComments/17641124",
    "score": 8,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 61,
    "username": "@desu_chaan",
    "title": "Работа #61",
    "image": "img/works/061_desu_chaan.webp",
    "postLink": "https://t.me/StableWaifuComments/17655631",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 62,
    "username": "@desu_chaan",
    "title": "Работа #62",
    "image": "img/works/062_desu_chaan.webp",
    "postLink": "https://t.me/StableWaifuComments/17655633",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 63,
    "username": "@desu_chaan",
    "title": "Работа #63",
    "image": "img/works/063_desu_chaan.webp",
    "postLink": "https://t.me/StableWaifuComments/17655636",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 64,
    "username": "@desu_chaan",
    "title": "Работа #64",
    "image": "img/works/064_desu_chaan.webp",
    "postLink": "https://t.me/StableWaifuComments/17655642",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 65,
    "username": "@desu_chaan",
    "title": "Работа #65",
    "image": "img/works/065_desu_chaan.webp",
    "postLink": "https://t.me/StableWaifuComments/17655743",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 66,
    "username": "@desu_chaan",
    "title": "Работа #66",
    "image": "img/works/066_desu_chaan.webp",
    "postLink": "https://t.me/StableWaifuComments/17655754",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 67,
    "username": "@desu_chaan",
    "title": "Работа #67",
    "image": "img/works/067_desu_chaan.webp",
    "postLink": "https://t.me/StableWaifuComments/17663171",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 68,
    "username": "@desu_chaan",
    "title": "Работа #68",
    "image": "img/works/068_desu_chaan.webp",
    "postLink": "https://t.me/StableWaifuComments/17663883",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 69,
    "username": "@desu_chaan",
    "title": "Работа #69",
    "image": "img/works/069_desu_chaan.webp",
    "postLink": "https://t.me/StableWaifuComments/17662963",
    "score": 8,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 70,
    "username": "@eeepolz",
    "title": "Работа #70",
    "image": "img/works/070_eeepolz.webp",
    "postLink": "https://t.me/StableWaifuComments/17626366",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 71,
    "username": "@eeepolz",
    "title": "Работа #71",
    "image": "img/works/071_eeepolz.webp",
    "postLink": "https://t.me/StableWaifuComments/17626366",
    "score": 6,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 72,
    "username": "@Erika_Demons_moon",
    "title": "Работа #72",
    "image": "img/works/072_Erika_Demons_moon.webp",
    "postLink": "https://t.me/StableWaifuComments/17640066",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 73,
    "username": "@Erika_Demons_moon",
    "title": "Работа #73",
    "image": "img/works/073_Erika_Demons_moon.webp",
    "postLink": "https://t.me/StableWaifuComments/17641321",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 74,
    "username": "@Erika_Demons_moon",
    "title": "Работа #74",
    "image": "img/works/074_Erika_Demons_moon.webp",
    "postLink": "https://t.me/StableWaifuComments/17654624",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 75,
    "username": "@Erika_Demons_moon",
    "title": "Работа #75",
    "image": "img/works/075_Erika_Demons_moon.webp",
    "postLink": "https://t.me/StableWaifuComments/17654811",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 76,
    "username": "@Erika_Demons_moon",
    "title": "Работа #76",
    "image": "img/works/076_Erika_Demons_moon.webp",
    "postLink": "https://t.me/StableWaifuComments/17658906",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 77,
    "username": "@Erika_Demons_moon",
    "title": "Работа #77",
    "image": "img/works/077_Erika_Demons_moon.webp",
    "postLink": "https://t.me/StableWaifuComments/17663775",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 78,
    "username": "@Erika_Demons_moon",
    "title": "Работа #78",
    "image": "img/works/078_Erika_Demons_moon.webp",
    "postLink": "https://t.me/StableWaifuComments/17657838",
    "score": 8,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 79,
    "username": "@Fadia_My_Wife",
    "title": "Работа #79",
    "image": "img/works/079_Fadia_My_Wife.webp",
    "postLink": "https://t.me/StableWaifuComments/17626837",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 80,
    "username": "@Fadia_My_Wife",
    "title": "Работа #80",
    "image": "img/works/080_Fadia_My_Wife.webp",
    "postLink": "https://t.me/StableWaifuComments/17658114",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 81,
    "username": "@Fadia_My_Wife",
    "title": "Работа #81",
    "image": "img/works/081_Fadia_My_Wife.webp",
    "postLink": "https://t.me/StableWaifuComments/17633932",
    "score": 10,
    "reward": 1300,
    "isWinner": true,
    "place": 2,
    "awardTitle": "Silver Moon"
  },
  {
    "id": 82,
    "username": "@forLansely",
    "title": "Работа #82",
    "image": "img/works/082_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17627002",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 83,
    "username": "@forLansely",
    "title": "Работа #83",
    "image": "img/works/083_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17627744",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 84,
    "username": "@forLansely",
    "title": "Работа #84",
    "image": "img/works/084_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17628205",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 85,
    "username": "@forLansely",
    "title": "Работа #85",
    "image": "img/works/085_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17637035",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 86,
    "username": "@forLansely",
    "title": "Работа #86",
    "image": "img/works/086_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17637650",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 87,
    "username": "@forLansely",
    "title": "Работа #87",
    "image": "img/works/087_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17638265",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 88,
    "username": "@forLansely",
    "title": "Работа #88",
    "image": "img/works/088_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17643148",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 89,
    "username": "@forLansely",
    "title": "Работа #89",
    "image": "img/works/089_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17643259",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 90,
    "username": "@forLansely",
    "title": "Работа #90",
    "image": "img/works/090_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17654350",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 91,
    "username": "@forLansely",
    "title": "Работа #91",
    "image": "img/works/091_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17662092",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 92,
    "username": "@forLansely",
    "title": "Работа #92",
    "image": "img/works/092_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17662197",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 93,
    "username": "@forLansely",
    "title": "Работа #93",
    "image": "img/works/093_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17662339",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 94,
    "username": "@forLansely",
    "title": "Работа #94",
    "image": "img/works/094_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17662597",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 95,
    "username": "@forLansely",
    "title": "Работа #95",
    "image": "img/works/095_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17662808",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 96,
    "username": "@forLansely",
    "title": "Работа #96",
    "image": "img/works/096_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17662836",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 97,
    "username": "@forLansely",
    "title": "Работа #97",
    "image": "img/works/097_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17663486",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 98,
    "username": "@forLansely",
    "title": "Работа #98",
    "image": "img/works/098_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17663974",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 99,
    "username": "@forLansely",
    "title": "Работа #99",
    "image": "img/works/099_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17664115",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 100,
    "username": "@forLansely",
    "title": "Работа #100",
    "image": "img/works/100_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17663747",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 101,
    "username": "@forLansely",
    "title": "Работа #101",
    "image": "img/works/101_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17664426",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 102,
    "username": "@forLansely",
    "title": "Работа #102",
    "image": "img/works/102_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17661671",
    "score": 10,
    "reward": 2100,
    "isWinner": true,
    "place": 1,
    "awardTitle": "Grand Winner"
  },
  {
    "id": 103,
    "username": "@funtik_suka",
    "title": "Работа #103",
    "image": "img/works/103_funtik_suka.webp",
    "postLink": "https://t.me/StableWaifuComments/17630251",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 104,
    "username": "@funtik_suka",
    "title": "Работа #104",
    "image": "img/works/104_funtik_suka.webp",
    "postLink": "https://t.me/StableWaifuComments/17642228",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 105,
    "username": "@funtik_suka",
    "title": "Работа #105",
    "image": "img/works/105_funtik_suka.webp",
    "postLink": "https://t.me/StableWaifuComments/17642457",
    "score": 10,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 106,
    "username": "@i_know_worthless_man",
    "title": "Работа #106",
    "image": "img/works/106_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17630474",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 107,
    "username": "@i_know_worthless_man",
    "title": "Работа #107",
    "image": "img/works/107_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17631629",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 108,
    "username": "@i_know_worthless_man",
    "title": "Работа #108",
    "image": "img/works/108_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17634021",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 109,
    "username": "@i_know_worthless_man",
    "title": "Работа #109",
    "image": "img/works/109_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17634300",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 110,
    "username": "@i_know_worthless_man",
    "title": "Работа #110",
    "image": "img/works/110_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17634944",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 111,
    "username": "@i_know_worthless_man",
    "title": "Работа #111",
    "image": "img/works/111_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17643104",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 112,
    "username": "@i_know_worthless_man",
    "title": "Работа #112",
    "image": "img/works/112_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17643655",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 113,
    "username": "@i_know_worthless_man",
    "title": "Работа #113",
    "image": "img/works/113_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17644002",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 114,
    "username": "@i_know_worthless_man",
    "title": "Работа #114",
    "image": "img/works/114_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17644832",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 115,
    "username": "@i_know_worthless_man",
    "title": "Работа #115",
    "image": "img/works/115_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17647817",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 116,
    "username": "@i_know_worthless_man",
    "title": "Работа #116",
    "image": "img/works/116_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17648220",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 117,
    "username": "@i_know_worthless_man",
    "title": "Работа #117",
    "image": "img/works/117_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17648879",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 118,
    "username": "@i_know_worthless_man",
    "title": "Работа #118",
    "image": "img/works/118_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17649071",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 119,
    "username": "@i_know_worthless_man",
    "title": "Работа #119",
    "image": "img/works/119_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17649132",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 120,
    "username": "@i_know_worthless_man",
    "title": "Работа #120",
    "image": "img/works/120_i_know_worthless_man.webp",
    "postLink": "https://t.me/StableWaifuComments/17654995",
    "score": 9,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 121,
    "username": "@kak_sad_lox",
    "title": "Работа #121",
    "image": "img/works/121_kak_sad_lox.webp",
    "postLink": "https://t.me/StableWaifuComments/17636663",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 122,
    "username": "@kak_sad_lox",
    "title": "Работа #122",
    "image": "img/works/122_kak_sad_lox.webp",
    "postLink": "https://t.me/StableWaifuComments/17637183",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 123,
    "username": "@kak_sad_lox",
    "title": "Работа #123",
    "image": "img/works/123_kak_sad_lox.webp",
    "postLink": "https://t.me/StableWaifuComments/17639432",
    "score": 8,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 124,
    "username": "@kirillmvpp",
    "title": "Работа #124",
    "image": "img/works/124_kirillmvpp.webp",
    "postLink": "https://t.me/StableWaifuComments/17638354",
    "score": 10,
    "reward": 1300,
    "isWinner": true,
    "place": 2,
    "awardTitle": "Silver Moon"
  },
  {
    "id": 125,
    "username": "@Kuro_niga",
    "title": "Работа #125",
    "image": "img/works/125_Kuro_niga.webp",
    "postLink": "https://t.me/StableWaifuComments/17641127",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 126,
    "username": "@Kuro_niga",
    "title": "Работа #126",
    "image": "img/works/126_Kuro_niga.webp",
    "postLink": "https://t.me/StableWaifuComments/17641171",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 127,
    "username": "@Kuro_niga",
    "title": "Работа #127",
    "image": "img/works/127_Kuro_niga.webp",
    "postLink": "https://t.me/StableWaifuComments/17641171?single",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 128,
    "username": "@Kuro_niga",
    "title": "Работа #128",
    "image": "img/works/128_Kuro_niga.webp",
    "postLink": "https://t.me/StableWaifuComments/17641214",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 129,
    "username": "@Kuro_niga",
    "title": "Работа #129",
    "image": "img/works/129_Kuro_niga.webp",
    "postLink": "https://t.me/StableWaifuComments/17640886",
    "score": 7,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 130,
    "username": "@lissa_ellesi",
    "title": "Работа #130",
    "image": "img/works/130_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17624443",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 131,
    "username": "@lissa_ellesi",
    "title": "Работа #131",
    "image": "img/works/131_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17624583",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 132,
    "username": "@lissa_ellesi",
    "title": "Работа #132",
    "image": "img/works/132_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17624688",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 133,
    "username": "@lissa_ellesi",
    "title": "Работа #133",
    "image": "img/works/133_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17624914",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 134,
    "username": "@lissa_ellesi",
    "title": "Работа #134",
    "image": "img/works/134_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17625362",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 135,
    "username": "@lissa_ellesi",
    "title": "Работа #135",
    "image": "img/works/135_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17625375",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 136,
    "username": "@lissa_ellesi",
    "title": "Работа #136",
    "image": "img/works/136_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17625419",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 137,
    "username": "@lissa_ellesi",
    "title": "Работа #137",
    "image": "img/works/137_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17637803",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 138,
    "username": "@lissa_ellesi",
    "title": "Работа #138",
    "image": "img/works/138_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17637839",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 139,
    "username": "@lissa_ellesi",
    "title": "Работа #139",
    "image": "img/works/139_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17638651",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 140,
    "username": "@lissa_ellesi",
    "title": "Работа #140",
    "image": "img/works/140_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17661348",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 141,
    "username": "@lissa_ellesi",
    "title": "Работа #141",
    "image": "img/works/141_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17661387",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 142,
    "username": "@lissa_ellesi",
    "title": "Работа #142",
    "image": "img/works/142_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17661945",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 143,
    "username": "@lissa_ellesi",
    "title": "Работа #143",
    "image": "img/works/143_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17662036",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 144,
    "username": "@lissa_ellesi",
    "title": "Работа #144",
    "image": "img/works/144_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17662041",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 145,
    "username": "@lissa_ellesi",
    "title": "Работа #145",
    "image": "img/works/145_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17662524",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 146,
    "username": "@lissa_ellesi",
    "title": "Работа #146",
    "image": "img/works/146_lissa_ellesi.webp",
    "postLink": "https://t.me/StableWaifuComments/17633909",
    "score": 10,
    "reward": 1300,
    "isWinner": true,
    "place": 2,
    "awardTitle": "Silver Moon"
  },
  {
    "id": 147,
    "username": "@macsheacaich",
    "title": "Работа #147",
    "image": "img/works/147_macsheacaich.webp",
    "postLink": "https://t.me/StableWaifuComments/17656851",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 148,
    "username": "@macsheacaich",
    "title": "Работа #148",
    "image": "img/works/148_macsheacaich.webp",
    "postLink": "https://t.me/StableWaifuComments/17658487",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 149,
    "username": "@macsheacaich",
    "title": "Работа #149",
    "image": "img/works/149_macsheacaich.webp",
    "postLink": "https://t.me/StableWaifuComments/17653896",
    "score": 7,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 150,
    "username": "@Malkov_tt",
    "title": "Работа #150",
    "image": "img/works/150_Malkov_tt.webp",
    "postLink": "https://t.me/StableWaifuComments/17627613",
    "score": 7,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 151,
    "username": "@mamkin_besoeb_228",
    "title": "Работа #151",
    "image": "img/works/151_mamkin_besoeb_228.webp",
    "postLink": "https://t.me/StableWaifuComments/17623885",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 152,
    "username": "@mamkin_besoeb_228",
    "title": "Работа #152",
    "image": "img/works/152_mamkin_besoeb_228.webp",
    "postLink": "https://t.me/StableWaifuComments/17624033",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 153,
    "username": "@mamkin_besoeb_228",
    "title": "Работа #153",
    "image": "img/works/153_mamkin_besoeb_228.webp",
    "postLink": "https://t.me/StableWaifuComments/17624141",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 154,
    "username": "@mamkin_besoeb_228",
    "title": "Работа #154",
    "image": "img/works/154_mamkin_besoeb_228.webp",
    "postLink": "https://t.me/StableWaifuComments/17642037",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 155,
    "username": "@mamkin_besoeb_228",
    "title": "Работа #155",
    "image": "img/works/155_mamkin_besoeb_228.webp",
    "postLink": "https://t.me/StableWaifuComments/17642802",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 156,
    "username": "@mamkin_besoeb_228",
    "title": "Работа #156",
    "image": "img/works/156_mamkin_besoeb_228.webp",
    "postLink": "https://t.me/StableWaifuComments/17664266",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 157,
    "username": "@mamkin_besoeb_228",
    "title": "Работа #157",
    "image": "img/works/157_mamkin_besoeb_228.webp",
    "postLink": "https://t.me/StableWaifuComments/17644111",
    "score": 9,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 158,
    "username": "@Mic_fn",
    "title": "Работа #158",
    "image": "img/works/158_Mic_fn.webp",
    "postLink": "https://t.me/StableWaifuComments/17629992",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 159,
    "username": "@Mic_fn",
    "title": "Работа #159",
    "image": "img/works/159_Mic_fn.webp",
    "postLink": "https://t.me/StableWaifuComments/17629991",
    "score": 7,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 160,
    "username": "@Missambi",
    "title": "Работа #160",
    "image": "img/works/160_Missambi.webp",
    "postLink": "https://t.me/StableWaifuComments/17624159",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 161,
    "username": "@Missambi",
    "title": "Работа #161",
    "image": "img/works/161_Missambi.webp",
    "postLink": "https://t.me/StableWaifuComments/17624282",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 162,
    "username": "@Missambi",
    "title": "Работа #162",
    "image": "img/works/162_Missambi.webp",
    "postLink": "https://t.me/StableWaifuComments/17624356",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 163,
    "username": "@Missambi",
    "title": "Работа #163",
    "image": "img/works/163_Missambi.webp",
    "postLink": "https://t.me/StableWaifuComments/17653675",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 164,
    "username": "@Missambi",
    "title": "Работа #164",
    "image": "img/works/164_Missambi.webp",
    "postLink": "https://t.me/StableWaifuComments/17655135",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 165,
    "username": "@Missambi",
    "title": "Работа #165",
    "image": "img/works/165_Missambi.webp",
    "postLink": "https://t.me/StableWaifuComments/17655214",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 166,
    "username": "@Missambi",
    "title": "Работа #166",
    "image": "img/works/166_Missambi.webp",
    "postLink": "https://t.me/StableWaifuComments/17661889",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 167,
    "username": "@Missambi",
    "title": "Работа #167",
    "image": "img/works/167_Missambi.webp",
    "postLink": "https://t.me/StableWaifuComments/17655416",
    "score": 10,
    "reward": 1300,
    "isWinner": true,
    "place": 2,
    "awardTitle": "Silver Moon"
  },
  {
    "id": 168,
    "username": "@mmoonnssttrrr",
    "title": "Работа #168",
    "image": "img/works/168_mmoonnssttrrr.webp",
    "postLink": "https://t.me/StableWaifuComments/17626529",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 169,
    "username": "@mmoonnssttrrr",
    "title": "Работа #169",
    "image": "img/works/169_mmoonnssttrrr.webp",
    "postLink": "https://t.me/StableWaifuComments/17626580",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 170,
    "username": "@mmoonnssttrrr",
    "title": "Работа #170",
    "image": "img/works/170_mmoonnssttrrr.webp",
    "postLink": "https://t.me/StableWaifuComments/17658665",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 171,
    "username": "@mmoonnssttrrr",
    "title": "Работа #171",
    "image": "img/works/171_mmoonnssttrrr.webp",
    "postLink": "https://t.me/StableWaifuComments/17650517",
    "score": 7,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 172,
    "username": "@Muzan_CTE",
    "title": "Работа #172",
    "image": "img/works/172_Muzan_CTE.webp",
    "postLink": "https://t.me/StableWaifuComments/17660256",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 173,
    "username": "@Muzan_CTE",
    "title": "Работа #173",
    "image": "img/works/173_Muzan_CTE.webp",
    "postLink": "https://t.me/StableWaifuComments/17660319",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 174,
    "username": "@Muzan_CTE",
    "title": "Работа #174",
    "image": "img/works/174_Muzan_CTE.webp",
    "postLink": "https://t.me/StableWaifuComments/17660563",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 175,
    "username": "@Muzan_CTE",
    "title": "Работа #175",
    "image": "img/works/175_Muzan_CTE.webp",
    "postLink": "https://t.me/StableWaifuComments/17660721",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 176,
    "username": "@Muzan_CTE",
    "title": "Работа #176",
    "image": "img/works/176_Muzan_CTE.webp",
    "postLink": "https://t.me/StableWaifuComments/17660803",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 177,
    "username": "@Muzan_CTE",
    "title": "Работа #177",
    "image": "img/works/177_Muzan_CTE.webp",
    "postLink": "https://t.me/StableWaifuComments/17660461",
    "score": 7,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 178,
    "username": "@Nunasw",
    "title": "Работа #178",
    "image": "img/works/178_Nunasw.webp",
    "postLink": "https://t.me/StableWaifuComments/17636145",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 179,
    "username": "@Nunasw",
    "title": "Работа #179",
    "image": "img/works/179_Nunasw.webp",
    "postLink": "https://t.me/StableWaifuComments/17636154",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 180,
    "username": "@Nunasw",
    "title": "Работа #180",
    "image": "img/works/180_Nunasw.webp",
    "postLink": "https://t.me/StableWaifuComments/17636162",
    "score": 10,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 181,
    "username": "@Phantom_YoRHa",
    "title": "Работа #181",
    "image": "img/works/181_Phantom_YoRHa.webp",
    "postLink": "https://t.me/StableWaifuComments/17658593",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 182,
    "username": "@Phantom_YoRHa",
    "title": "Работа #182",
    "image": "img/works/182_Phantom_YoRHa.webp",
    "postLink": "https://t.me/StableWaifuComments/17660186",
    "score": 7,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 183,
    "username": "@PolPolaNaPolu",
    "title": "Работа #183",
    "image": "img/works/183_PolPolaNaPolu.webp",
    "postLink": "https://t.me/StableWaifuComments/17659819",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 184,
    "username": "@PolPolaNaPolu",
    "title": "Работа #184",
    "image": "img/works/184_PolPolaNaPolu.webp",
    "postLink": "https://t.me/StableWaifuComments/17659847",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 185,
    "username": "@PolPolaNaPolu",
    "title": "Работа #185",
    "image": "img/works/185_PolPolaNaPolu.webp",
    "postLink": "https://t.me/StableWaifuComments/17660315",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 186,
    "username": "@PolPolaNaPolu",
    "title": "Работа #186",
    "image": "img/works/186_PolPolaNaPolu.webp",
    "postLink": "https://t.me/StableWaifuComments/17659826",
    "score": 9,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 187,
    "username": "@Ricky314159",
    "title": "Работа #187",
    "image": "img/works/187_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17638057",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 188,
    "username": "@Ricky314159",
    "title": "Работа #188",
    "image": "img/works/188_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17639873",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 189,
    "username": "@Ricky314159",
    "title": "Работа #189",
    "image": "img/works/189_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17640019",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 190,
    "username": "@Ricky314159",
    "title": "Работа #190",
    "image": "img/works/190_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17640104",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 191,
    "username": "@Ricky314159",
    "title": "Работа #191",
    "image": "img/works/191_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17640190",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 192,
    "username": "@Ricky314159",
    "title": "Работа #192",
    "image": "img/works/192_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17640369",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 193,
    "username": "@Ricky314159",
    "title": "Работа #193",
    "image": "img/works/193_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17640668",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 194,
    "username": "@Ricky314159",
    "title": "Работа #194",
    "image": "img/works/194_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17641091",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 195,
    "username": "@Ricky314159",
    "title": "Работа #195",
    "image": "img/works/195_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17649854",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 196,
    "username": "@Ricky314159",
    "title": "Работа #196",
    "image": "img/works/196_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17651895",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 197,
    "username": "@Ricky314159",
    "title": "Работа #197",
    "image": "img/works/197_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17663309",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 198,
    "username": "@Ricky314159",
    "title": "Работа #198",
    "image": "img/works/198_Ricky314159.webp",
    "postLink": "https://t.me/StableWaifuComments/17637930",
    "score": 9,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 199,
    "username": "@Rina_ds",
    "title": "Работа #199",
    "image": "img/works/199_Rina_ds.webp",
    "postLink": "https://t.me/StableWaifuComments/17626771",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 200,
    "username": "@Rina_ds",
    "title": "Работа #200",
    "image": "img/works/200_Rina_ds.webp",
    "postLink": "https://t.me/StableWaifuComments/17626899",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 201,
    "username": "@Rina_ds",
    "title": "Работа #201",
    "image": "img/works/201_Rina_ds.webp",
    "postLink": "https://t.me/StableWaifuComments/17628679",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 202,
    "username": "@Rina_ds",
    "title": "Работа #202",
    "image": "img/works/202_Rina_ds.webp",
    "postLink": "https://t.me/StableWaifuComments/17628685",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 203,
    "username": "@Rina_ds",
    "title": "Работа #203",
    "image": "img/works/203_Rina_ds.webp",
    "postLink": "https://t.me/StableWaifuComments/17658045",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 204,
    "username": "@Rina_ds",
    "title": "Работа #204",
    "image": "img/works/204_Rina_ds.webp",
    "postLink": "https://t.me/StableWaifuComments/17658095",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 205,
    "username": "@Rina_ds",
    "title": "Работа #205",
    "image": "img/works/205_Rina_ds.webp",
    "postLink": "https://t.me/StableWaifuComments/17628671",
    "score": 9,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 206,
    "username": "@rumishii",
    "title": "Работа #206",
    "image": "img/works/206_rumishii.webp",
    "postLink": "https://t.me/StableWaifuComments/17628660",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 207,
    "username": "@rumishii",
    "title": "Работа #207",
    "image": "img/works/207_rumishii.webp",
    "postLink": "https://t.me/StableWaifuComments/17664256",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 208,
    "username": "@rumishii",
    "title": "Работа #208",
    "image": "img/works/208_rumishii.webp",
    "postLink": "https://t.me/StableWaifuComments/17664229",
    "score": 9,
    "reward": 900,
    "isWinner": true,
    "place": 3,
    "awardTitle": "Bronze Feather"
  },
  {
    "id": 209,
    "username": "@sarah_dranelone",
    "title": "Работа #209",
    "image": "img/works/209_sarah_dranelone.webp",
    "postLink": "https://t.me/StableWaifuComments/17624524",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 210,
    "username": "@sarah_dranelone",
    "title": "Работа #210",
    "image": "img/works/210_sarah_dranelone.webp",
    "postLink": "https://t.me/StableWaifuComments/17624354",
    "score": 7,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 211,
    "username": "@Sheep4ik",
    "title": "Работа #211",
    "image": "img/works/211_Sheep4ik.webp",
    "postLink": "https://t.me/StableWaifuComments/17660860",
    "score": 3,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 212,
    "username": "@Sheep4ik",
    "title": "Работа #212",
    "image": "img/works/212_Sheep4ik.webp",
    "postLink": "https://t.me/StableWaifuComments/17660754",
    "score": 7,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 213,
    "username": "@StaXiao1",
    "title": "Работа #213",
    "image": "img/works/213_StaXiao1.webp",
    "postLink": "https://t.me/StableWaifuComments/17627531",
    "score": 7,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 214,
    "username": "@the_elv",
    "title": "Работа #214",
    "image": "img/works/214_the_elv.webp",
    "postLink": "https://t.me/StableWaifuComments/17624166",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 215,
    "username": "@the_elv",
    "title": "Работа #215",
    "image": "img/works/215_the_elv.webp",
    "postLink": "https://t.me/StableWaifuComments/17627543",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 216,
    "username": "@the_elv",
    "title": "Работа #216",
    "image": "img/works/216_the_elv.webp",
    "postLink": "https://t.me/StableWaifuComments/17629796",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 217,
    "username": "@the_elv",
    "title": "Работа #217",
    "image": "img/works/217_the_elv.webp",
    "postLink": "https://t.me/StableWaifuComments/17631395",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 218,
    "username": "@the_elv",
    "title": "Работа #218",
    "image": "img/works/218_the_elv.webp",
    "postLink": "https://t.me/StableWaifuComments/17636008",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 219,
    "username": "@the_elv",
    "title": "Работа #219",
    "image": "img/works/219_the_elv.webp",
    "postLink": "https://t.me/StableWaifuComments/17637821",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 220,
    "username": "@the_elv",
    "title": "Работа #220",
    "image": "img/works/220_the_elv.webp",
    "postLink": "https://t.me/StableWaifuComments/17646385",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 221,
    "username": "@the_elv",
    "title": "Работа #221",
    "image": "img/works/221_the_elv.webp",
    "postLink": "https://t.me/StableWaifuComments/17664119",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 222,
    "username": "@the_elv",
    "title": "Работа #222",
    "image": "img/works/222_the_elv.webp",
    "postLink": "https://t.me/StableWaifuComments/17630246",
    "score": 10,
    "reward": 2100,
    "isWinner": true,
    "place": 1,
    "awardTitle": "Grand Winner"
  },
  {
    "id": 223,
    "username": "@tinyEngel",
    "title": "Работа #223",
    "image": "img/works/223_tinyEngel.webp",
    "postLink": "https://t.me/StableWaifuComments/17626348",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 224,
    "username": "@tinyEngel",
    "title": "Работа #224",
    "image": "img/works/224_tinyEngel.webp",
    "postLink": "https://t.me/StableWaifuComments/17626352",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 225,
    "username": "@tinyEngel",
    "title": "Работа #225",
    "image": "img/works/225_tinyEngel.webp",
    "postLink": "https://t.me/StableWaifuComments/17626426",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 226,
    "username": "@tinyEngel",
    "title": "Работа #226",
    "image": "img/works/226_tinyEngel.webp",
    "postLink": "https://t.me/StableWaifuComments/17626486",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 227,
    "username": "@tinyEngel",
    "title": "Работа #227",
    "image": "img/works/227_tinyEngel.webp",
    "postLink": "https://t.me/StableWaifuComments/17626519",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 228,
    "username": "@tinyEngel",
    "title": "Работа #228",
    "image": "img/works/228_tinyEngel.webp",
    "postLink": "https://t.me/StableWaifuComments/17626752",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 229,
    "username": "@tinyEngel",
    "title": "Работа #229",
    "image": "img/works/229_tinyEngel.webp",
    "postLink": "https://t.me/StableWaifuComments/17626971",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 230,
    "username": "@tinyEngel",
    "title": "Работа #230",
    "image": "img/works/230_tinyEngel.webp",
    "postLink": "https://t.me/StableWaifuComments/17627247",
    "score": 9,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 231,
    "username": "@Tushkanchik_16",
    "title": "Работа #231",
    "image": "img/works/231_Tushkanchik_16.webp",
    "postLink": "https://t.me/StableWaifuComments/17635464",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 232,
    "username": "@Tushkanchik_16",
    "title": "Работа #232",
    "image": "img/works/232_Tushkanchik_16.webp",
    "postLink": "https://t.me/StableWaifuComments/17636076",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 233,
    "username": "@Tushkanchik_16",
    "title": "Работа #233",
    "image": "img/works/233_Tushkanchik_16.webp",
    "postLink": "https://t.me/StableWaifuComments/17636114",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 234,
    "username": "@Tushkanchik_16",
    "title": "Работа #234",
    "image": "img/works/234_Tushkanchik_16.webp",
    "postLink": "https://t.me/StableWaifuComments/17636182",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 235,
    "username": "@Tushkanchik_16",
    "title": "Работа #235",
    "image": "img/works/235_Tushkanchik_16.webp",
    "postLink": "https://t.me/StableWaifuComments/17653373",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 236,
    "username": "@Tushkanchik_16",
    "title": "Работа #236",
    "image": "img/works/236_Tushkanchik_16.webp",
    "postLink": "https://t.me/StableWaifuComments/17653483",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 237,
    "username": "@Tushkanchik_16",
    "title": "Работа #237",
    "image": "img/works/237_Tushkanchik_16.webp",
    "postLink": "https://t.me/StableWaifuComments/17632019",
    "score": 8,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 238,
    "username": "@vedzmak",
    "title": "Работа #238",
    "image": "img/works/238_vedzmak.webp",
    "postLink": "https://t.me/StableWaifuComments/17658673",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 239,
    "username": "@vedzmak",
    "title": "Работа #239",
    "image": "img/works/239_vedzmak.webp",
    "postLink": "https://t.me/StableWaifuComments/17658680",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 240,
    "username": "@vedzmak",
    "title": "Работа #240",
    "image": "img/works/240_vedzmak.webp",
    "postLink": "https://t.me/StableWaifuComments/17658718",
    "score": 5,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 241,
    "username": "@vedzmak",
    "title": "Работа #241",
    "image": "img/works/241_vedzmak.webp",
    "postLink": "https://t.me/StableWaifuComments/17658792",
    "score": 4,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 242,
    "username": "@vedzmak",
    "title": "Работа #242",
    "image": "img/works/242_vedzmak.webp",
    "postLink": "https://t.me/StableWaifuComments/17658482",
    "score": 6,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 243,
    "username": "@vivka_wuu",
    "title": "Работа #243",
    "image": "img/works/243_vivka_wuu.webp",
    "postLink": "https://t.me/StableWaifuComments/17629532",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 244,
    "username": "@vivka_wuu",
    "title": "Работа #244",
    "image": "img/works/244_vivka_wuu.webp",
    "postLink": "https://t.me/StableWaifuComments/17629692",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 245,
    "username": "@vivka_wuu",
    "title": "Работа #245",
    "image": "img/works/245_vivka_wuu.webp",
    "postLink": "https://t.me/StableWaifuComments/17638894",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 246,
    "username": "@vivka_wuu",
    "title": "Работа #246",
    "image": "img/works/246_vivka_wuu.webp",
    "postLink": "https://t.me/StableWaifuComments/17647763",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 247,
    "username": "@vivka_wuu",
    "title": "Работа #247",
    "image": "img/works/247_vivka_wuu.webp",
    "postLink": "https://t.me/StableWaifuComments/17655206",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 248,
    "username": "@vivka_wuu",
    "title": "Работа #248",
    "image": "img/works/248_vivka_wuu.webp",
    "postLink": "https://t.me/StableWaifuComments/17660594",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 249,
    "username": "@vivka_wuu",
    "title": "Работа #249",
    "image": "img/works/249_vivka_wuu.webp",
    "postLink": "https://t.me/StableWaifuComments/17636621",
    "score": 9,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 250,
    "username": "@wwwvvvwvv",
    "title": "Работа #250",
    "image": "img/works/250_wwwvvvwvv.webp",
    "postLink": "https://t.me/StableWaifuComments/17632692",
    "score": 8,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 251,
    "username": "@Xomiakpro444",
    "title": "Работа #251",
    "image": "img/works/251_Xomiakpro444.webp",
    "postLink": "https://t.me/StableWaifuComments/17649488",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 252,
    "username": "@Xomiakpro444",
    "title": "Работа #252",
    "image": "img/works/252_Xomiakpro444.webp",
    "postLink": "https://t.me/StableWaifuComments/17625491",
    "score": 7,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 253,
    "username": "@YormiFB",
    "title": "Работа #253",
    "image": "img/works/253_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17624119",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 254,
    "username": "@YormiFB",
    "title": "Работа #254",
    "image": "img/works/254_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17624135",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 255,
    "username": "@YormiFB",
    "title": "Работа #255",
    "image": "img/works/255_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17624274",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 256,
    "username": "@YormiFB",
    "title": "Работа #256",
    "image": "img/works/256_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17627227",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 257,
    "username": "@YormiFB",
    "title": "Работа #257",
    "image": "img/works/257_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17629552",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 258,
    "username": "@YormiFB",
    "title": "Работа #258",
    "image": "img/works/258_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17629591",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 259,
    "username": "@YormiFB",
    "title": "Работа #259",
    "image": "img/works/259_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17631839",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 260,
    "username": "@YormiFB",
    "title": "Работа #260",
    "image": "img/works/260_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17632054",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 261,
    "username": "@YormiFB",
    "title": "Работа #261",
    "image": "img/works/261_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17632236",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 262,
    "username": "@YormiFB",
    "title": "Работа #262",
    "image": "img/works/262_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17632478",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 263,
    "username": "@YormiFB",
    "title": "Работа #263",
    "image": "img/works/263_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17643962",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 264,
    "username": "@forLansely",
    "title": "Работа #264",
    "image": "img/works/264_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17655269",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 265,
    "username": "@forLansely",
    "title": "Работа #265",
    "image": "img/works/265_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17655489",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 266,
    "username": "@forLansely",
    "title": "Работа #266",
    "image": "img/works/266_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17655510",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 267,
    "username": "@forLansely",
    "title": "Работа #267",
    "image": "img/works/267_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17659416",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 268,
    "username": "@forLansely",
    "title": "Работа #268",
    "image": "img/works/268_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17661686",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 269,
    "username": "@forLansely",
    "title": "Работа #269",
    "image": "img/works/269_forLansely.webp",
    "postLink": "https://t.me/StableWaifuComments/17661784",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 270,
    "username": "@YormiFB",
    "title": "Работа #270",
    "image": "img/works/270_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17664267",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 271,
    "username": "@YormiFB",
    "title": "Работа #271",
    "image": "img/works/271_YormiFB.webp",
    "postLink": "https://t.me/StableWaifuComments/17644003",
    "score": 10,
    "reward": 1300,
    "isWinner": true,
    "place": 2,
    "awardTitle": "Silver Moon"
  },
  {
    "id": 272,
    "username": "@yoru_di_lin",
    "title": "Работа #272",
    "image": "img/works/272_yoru_di_lin.webp",
    "postLink": "https://t.me/StableWaifuComments/17625523",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 273,
    "username": "@yoru_di_lin",
    "title": "Работа #273",
    "image": "img/works/273_yoru_di_lin.webp",
    "postLink": "https://t.me/StableWaifuComments/17625500",
    "score": 6,
    "reward": 300,
    "isWinner": true,
    "place": 5,
    "awardTitle": "Special Mention"
  },
  {
    "id": 274,
    "username": "@Yuiguang_Lian",
    "title": "Работа #274",
    "image": "img/works/274_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17623211",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 275,
    "username": "@Yuiguang_Lian",
    "title": "Работа #275",
    "image": "img/works/275_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17623443",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 276,
    "username": "@Yuiguang_Lian",
    "title": "Работа #276",
    "image": "img/works/276_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17623620",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 277,
    "username": "@Yuiguang_Lian",
    "title": "Работа #277",
    "image": "img/works/277_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17624066",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 278,
    "username": "@Yuiguang_Lian",
    "title": "Работа #278",
    "image": "img/works/278_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17633039",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 279,
    "username": "@Yuiguang_Lian",
    "title": "Работа #279",
    "image": "img/works/279_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17633078",
    "score": 10,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 280,
    "username": "@Yuiguang_Lian",
    "title": "Работа #280",
    "image": "img/works/280_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17633885",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 281,
    "username": "@Yuiguang_Lian",
    "title": "Работа #281",
    "image": "img/works/281_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17633916",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 282,
    "username": "@Yuiguang_Lian",
    "title": "Работа #282",
    "image": "img/works/282_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17633988",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 283,
    "username": "@Yuiguang_Lian",
    "title": "Работа #283",
    "image": "img/works/283_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17642779",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 284,
    "username": "@Yuiguang_Lian",
    "title": "Работа #284",
    "image": "img/works/284_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17664191",
    "score": 9,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 285,
    "username": "@Yuiguang_Lian",
    "title": "Работа #285",
    "image": "img/works/285_Yuiguang_Lian.webp",
    "postLink": "https://t.me/StableWaifuComments/17623868",
    "score": 10,
    "reward": 2100,
    "isWinner": true,
    "place": 1,
    "awardTitle": "Grand Winner"
  },
  {
    "id": 286,
    "username": "Азизбек",
    "title": "Работа #286",
    "image": "img/works/286_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17630400",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 287,
    "username": "Азизбек",
    "title": "Работа #287",
    "image": "img/works/287_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17630410",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 288,
    "username": "Азизбек",
    "title": "Работа #288",
    "image": "img/works/288_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17630414",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 289,
    "username": "Азизбек",
    "title": "Работа #289",
    "image": "img/works/289_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17630418",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 290,
    "username": "Азизбек",
    "title": "Работа #290",
    "image": "img/works/290_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17639850",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 291,
    "username": "Азизбек",
    "title": "Работа #291",
    "image": "img/works/291_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17640138",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 292,
    "username": "Азизбек",
    "title": "Работа #292",
    "image": "img/works/292_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17640223",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 293,
    "username": "Азизбек",
    "title": "Работа #293",
    "image": "img/works/293_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17640293",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 294,
    "username": "Азизбек",
    "title": "Работа #294",
    "image": "img/works/294_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17640651",
    "score": 4,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 295,
    "username": "Азизбек",
    "title": "Работа #295",
    "image": "img/works/295_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17640711",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 296,
    "username": "Азизбек",
    "title": "Работа #296",
    "image": "img/works/296_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17641527",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 297,
    "username": "Азизбек",
    "title": "Работа #297",
    "image": "img/works/297_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17641543",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 298,
    "username": "Азизбек",
    "title": "Работа #298",
    "image": "img/works/298_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17648717",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 299,
    "username": "Азизбек",
    "title": "Работа #299",
    "image": "img/works/299_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17660578",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 300,
    "username": "Азизбек",
    "title": "Работа #300",
    "image": "img/works/300_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17661189",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 301,
    "username": "Азизбек",
    "title": "Работа #301",
    "image": "img/works/301_Азизбек.webp",
    "postLink": "https://t.me/StableWaifuComments/17638562",
    "score": 8,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  },
  {
    "id": 302,
    "username": "🪶",
    "title": "Работа #302",
    "image": "img/works/302_user.webp",
    "postLink": "https://t.me/StableWaifuComments/17651377",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 303,
    "username": "🪶",
    "title": "Работа #303",
    "image": "img/works/303_user.webp",
    "postLink": "https://t.me/StableWaifuComments/17651388",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 304,
    "username": "🪶",
    "title": "Работа #304",
    "image": "img/works/304_user.webp",
    "postLink": "https://t.me/StableWaifuComments/17651402",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 305,
    "username": "🪶",
    "title": "Работа #305",
    "image": "img/works/305_user.webp",
    "postLink": "https://t.me/StableWaifuComments/17651408",
    "score": 7,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 306,
    "username": "🪶",
    "title": "Работа #306",
    "image": "img/works/306_user.webp",
    "postLink": "https://t.me/StableWaifuComments/17664137",
    "score": 8,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 307,
    "username": "🪶",
    "title": "Работа #307",
    "image": "img/works/307_user.webp",
    "postLink": "https://t.me/StableWaifuComments/17664225",
    "score": 6,
    "reward": 0,
    "isWinner": false,
    "place": null,
    "awardTitle": ""
  },
  {
    "id": 308,
    "username": "🪶",
    "title": "Работа #308",
    "image": "img/works/308_user.webp",
    "postLink": "https://t.me/StableWaifuComments/17651353",
    "score": 8,
    "reward": 500,
    "isWinner": true,
    "place": 4,
    "awardTitle": "Special Mention"
  }
];
