
var app=document.getElementById("app"),lightbox=document.getElementById("lightbox"),lightboxImg=document.getElementById("lightbox-img"),lightboxClose=document.querySelector(".lightbox__close"),musicButton=document.getElementById("music-toggle"),bgMusic=document.getElementById("bg-music");
var currentPage=0,WORKS_PER_PAGE=12,triedAutoplay=false,isRouting=false,currentSort="score",currentFilter="all";
function getEventTitle(){return typeof EVENT!=="undefined"&&EVENT.title?EVENT.title:"COLUMBINA"}
function escapeHtml(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function formatTokens(v){return String(Number(v||0).toLocaleString("ru-RU"))+" токенов"}function getScore(w){return Number(w.score||0)}function getReward(w){return Number(w.reward||0)}
function getTotalReward(ws){return ws.reduce(function(s,w){return s+getReward(w)},0)}function getAverageScore(ws){if(!ws.length)return 0;return ws.reduce(function(s,w){return s+getScore(w)},0)/ws.length}
function getWinners(){return WORKS.filter(function(w){return w.isWinner}).sort(function(a,b){return Number(a.place||999)-Number(b.place||999)})}
function getFilteredAndSortedWorks(){var ws=WORKS.slice();if(currentFilter==="winners")ws=ws.filter(function(w){return w.isWinner});if(currentSort==="new")ws.sort(function(a,b){return Number(b.id||0)-Number(a.id||0)});else if(currentSort==="reward")ws.sort(function(a,b){return getReward(b)!==getReward(a)?getReward(b)-getReward(a):getScore(b)-getScore(a)});else ws.sort(function(a,b){return getScore(b)!==getScore(a)?getScore(b)-getScore(a):getReward(b)-getReward(a)});return ws}
function getRouteFromUrl(){return new URLSearchParams(window.location.search).get("page")||"home"}function urlFor(r){return r==="home"?window.location.pathname:window.location.pathname+"?page="+r}
function renderStatsBlock(){var total=WORKS.length,w=getWinners().length,avg=getAverageScore(WORKS).toFixed(1).replace(".",","),prize=getTotalReward(WORKS);return '<div class="stats-grid"><div class="stat-card"><span>Всего работ</span><b>'+total+'</b></div><div class="stat-card"><span>Победителей</span><b>'+w+'</b></div><div class="stat-card"><span>Средняя оценка</span><b>'+avg+'/10</b></div><div class="stat-card"><span>Призовой фонд</span><b>'+formatTokens(prize)+'</b></div></div>'}
function setAppHtml(h){app.innerHTML=h}
function renderHome(){setAppHtml('<section class="home"><div class="cover-shell"><div class="cover-card"><img class="cover-img" src="'+escapeHtml(EVENT.cover||"img/cover.png")+'" alt="Обложка"><div class="cover-overlay"><div class="kicker">event archive</div><h1>'+escapeHtml(getEventTitle())+'</h1><p>Итоги ивента</p><a class="main-btn" href="'+urlFor("results")+'" data-route="results">Итоги</a></div></div></div></section>')}
function renderResultsMenu(){setAppHtml('<section class="page"><div class="page-head"><div><div class="kicker">choose section</div><h2>Итоги ивента</h2><p>Два раздела архива: витрина победителей и полный список работ.</p></div></div>'+renderStatsBlock()+'<div class="menu-grid"><a class="menu-card menu-card--winners" href="'+urlFor("winners")+'" data-route="winners"><div class="menu-card__mark">Hall I</div><h3>Работы победителей</h3><p>Отдельная витрина лучших работ, мест и наград.</p><span>'+getWinners().length+' работ</span></a><a class="menu-card menu-card--all" href="'+urlFor("all")+'" data-route="all"><div class="menu-card__mark">Hall II</div><h3>Все работы участников</h3><p>Полный архив ивента с оценками по 10-балльной шкале.</p><span>'+WORKS.length+' работ</span></a></div></section>')}
function renderWinners(){var ws=getWinners(),first=ws.filter(function(w){return Number(w.place)===1}),st=ws.filter(function(w){return Number(w.place)===2||Number(w.place)===3}),other=ws.filter(function(w){return !w.place||Number(w.place)>3}),html="";if(first.length)html+='<div class="podium podium-first">'+first.map(renderWorkCard).join("")+'</div>';if(st.length)html+='<div class="podium podium-secondary">'+st.map(renderWorkCard).join("")+'</div>';if(other.length)html+='<div class="works-grid winners-grid">'+other.map(renderWorkCard).join("")+'</div>';setAppHtml('<section class="page"><div class="page-head"><div><a class="back" href="'+urlFor("results")+'" data-route="results">← Назад к итогам</a><div class="kicker">winner gallery</div><h2>Работы победителей</h2><p>Главная витрина ивента: места, оценки и награды.</p></div></div>'+(ws.length?html:'<div class="empty">Победители пока не добавлены в <b>data.js</b>.</div>')+'</section>');attachImageHandlers()}
function renderAllWorks(){currentPage=0;renderAllWorksPage()}
function renderAllWorksPage(){var ws=getFilteredAndSortedWorks(),pages=Math.max(1,Math.ceil(ws.length/WORKS_PER_PAGE)),start=currentPage*WORKS_PER_PAGE,pageWorks=ws.slice(start,start+WORKS_PER_PAGE);setAppHtml('<section class="page"><div class="page-head"><div><a class="back" href="'+urlFor("results")+'" data-route="results">← Назад к итогам</a><div class="kicker">complete archive</div><h2>Все работы участников</h2><p>Оценка выставлялась по 10-балльной шкале, без комментариев.</p></div></div><div class="toolbar"><button class="filter-btn '+(currentSort==="score"?"is-active":"")+'" data-sort="score">Сначала лучшие</button><button class="filter-btn '+(currentSort==="new"?"is-active":"")+'" data-sort="new">Сначала новые</button><button class="filter-btn '+(currentSort==="reward"?"is-active":"")+'" data-sort="reward">По награде</button><button class="filter-btn '+(currentFilter==="winners"?"is-active":"")+'" data-filter="winners">Только победители</button><button class="filter-btn '+(currentFilter==="all"?"is-active":"")+'" data-filter="all">Все</button></div>'+(ws.length?'<div class="works-grid">'+pageWorks.map(renderWorkCard).join("")+'</div>':'<div class="empty">Работы пока не добавлены в <b>data.js</b>.</div>')+'<div class="pagination"><button class="ghost-btn" id="prev-page" type="button">← Назад</button><span class="page-counter">'+(currentPage+1)+' / '+pages+'</span><button class="main-btn small" id="next-page" type="button">Дальше →</button></div><div class="thanks-block"><h3>Спасибо всем участникам '+escapeHtml(getEventTitle())+'.</h3><p>Каждая работа стала частью архива.</p></div></section>');setupToolbar();var prev=document.getElementById("prev-page"),next=document.getElementById("next-page");if(prev){prev.disabled=currentPage===0;prev.onclick=function(){if(currentPage>0){currentPage--;renderAllWorksPage();window.scrollTo({top:0,behavior:"smooth"})}}}if(next){next.disabled=currentPage>=pages-1;next.onclick=function(){if(currentPage<pages-1){currentPage++;renderAllWorksPage();window.scrollTo({top:0,behavior:"smooth"})}}}attachImageHandlers()}
function setupToolbar(){document.querySelectorAll("[data-sort]").forEach(function(b){b.onclick=function(){currentSort=b.getAttribute("data-sort");currentPage=0;renderAllWorksPage()}});document.querySelectorAll("[data-filter]").forEach(function(b){b.onclick=function(){currentFilter=b.getAttribute("data-filter");currentPage=0;renderAllWorksPage()}})}
function renderWorkCard(w){var wb=w.isWinner?'<div class="place-badge">'+(w.place?w.place+" место":"Победитель")+"</div>":"",link=w.postLink?'<a class="post-link" href="'+escapeHtml(w.postLink)+'" target="_blank" rel="noopener">Пост</a>':"";return '<article class="work-card"><button class="image-btn" data-image="'+escapeHtml(w.image)+'" data-alt="'+escapeHtml(w.username)+'"><img src="'+escapeHtml(w.image)+'" alt="Работа '+escapeHtml(w.username)+'" loading="lazy" decoding="async">'+wb+'</button><div class="work-body"><div class="work-top"><div><h3>'+escapeHtml(w.username)+'</h3><p>'+escapeHtml(w.title||"Работа участника")+'</p></div>'+link+'</div><div class="result-badges"><span class="result-badge result-score">Оценка <b>'+getScore(w)+'/10</b></span><span class="result-badge result-reward">Награда <b>'+formatTokens(w.reward)+'</b></span></div></div></article>'}
function renderByRoute(r){if(r==="results")return renderResultsMenu();if(r==="winners")return renderWinners();if(r==="all")return renderAllWorks();renderHome()}
function routeTo(r,push){if(isRouting)return;isRouting=true;if(push)window.history.pushState({},"",urlFor(r));app.classList.remove("route-enter");app.classList.add("route-exit");setTimeout(function(){renderByRoute(r);app.classList.remove("route-exit");app.classList.add("route-enter");setTimeout(function(){app.classList.remove("route-enter");isRouting=false},540)},260)}
function setupNavigation(){document.addEventListener("click",function(e){var l=e.target.closest("a[data-route]");if(!l)return;e.preventDefault();routeTo(l.getAttribute("data-route"),true)});window.addEventListener("popstate",function(){routeTo(getRouteFromUrl(),false)})}
function setupParallax(){if(!window.matchMedia||!window.matchMedia("(hover: hover)").matches)return;document.addEventListener("mousemove",function(e){var x=(e.clientX/window.innerWidth-.5)*14,y=(e.clientY/window.innerHeight-.5)*14;document.body.style.backgroundPosition=(50+x*.08)+"% "+(50+y*.08)+"%"})}
function attachImageHandlers(){document.querySelectorAll("[data-image]").forEach(function(b){b.onclick=function(){lightboxImg.src=b.getAttribute("data-image");lightboxImg.alt=b.getAttribute("data-alt")||"";lightbox.classList.add("is-open");lightbox.setAttribute("aria-hidden","false")}})}
function closeLightbox(){if(!lightbox||!lightboxImg)return;lightbox.classList.remove("is-open");lightbox.setAttribute("aria-hidden","true");lightboxImg.src=""}
if(lightboxClose)lightboxClose.addEventListener("click",closeLightbox);if(lightbox)lightbox.addEventListener("click",function(e){if(e.target===lightbox)closeLightbox()});document.addEventListener("keydown",function(e){if(e.key==="Escape")closeLightbox()});
function updateMusicButton(p){if(!musicButton)return;if(p){musicButton.textContent="♪ Музыка: вкл";musicButton.classList.remove("is-muted");musicButton.classList.add("is-playing")}else{musicButton.textContent="♪ Музыка";musicButton.classList.remove("is-playing");musicButton.classList.add("is-muted")}}
function tryStartMusic(){if(!bgMusic||triedAutoplay)return;triedAutoplay=true;bgMusic.volume=.35;var pr=bgMusic.play();if(pr&&typeof pr.then==="function")pr.then(function(){updateMusicButton(true)}).catch(function(){updateMusicButton(false);musicButton.textContent="♪ Нажми для музыки"})}
if(musicButton&&bgMusic){bgMusic.volume=.35;musicButton.addEventListener("click",function(){if(bgMusic.paused)bgMusic.play().then(function(){updateMusicButton(true)}).catch(function(){updateMusicButton(false)});else{bgMusic.pause();updateMusicButton(false)}});document.addEventListener("click",function once(){if(bgMusic.paused)bgMusic.play().then(function(){updateMusicButton(true)}).catch(function(){});document.removeEventListener("click",once)})}
function showIntro(){if(document.getElementById("intro"))return;var intro=document.createElement("div");intro.id="intro";intro.innerHTML='<div class="intro-box"><h1>'+escapeHtml(getEventTitle())+'</h1><p>loading archive...</p><div class="loader-line"><span></span></div></div>';document.body.appendChild(intro);setTimeout(function(){intro.classList.add("is-hidden");setTimeout(function(){if(intro.parentNode)intro.parentNode.removeChild(intro)},650)},1150)}
setupNavigation();setupParallax();showIntro();renderByRoute(getRouteFromUrl());app.classList.add("route-enter");tryStartMusic();
